[2023-10-31T16:43:01.646-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Bash_Operator.hola_clase scheduled__2023-10-31T00:00:00+00:00 [queued]>
[2023-10-31T16:43:01.662-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Bash_Operator.hola_clase scheduled__2023-10-31T00:00:00+00:00 [queued]>
[2023-10-31T16:43:01.663-0500] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-10-31T16:43:01.663-0500] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-10-31T16:43:01.663-0500] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-10-31T16:43:01.681-0500] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): hola_clase> on 2023-10-31 00:00:00+00:00
[2023-10-31T16:43:01.686-0500] {standard_task_runner.py:55} INFO - Started process 402422 to run task
[2023-10-31T16:43:01.692-0500] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Bash_Operator', 'hola_clase', 'scheduled__2023-10-31T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/bashOperator.py', '--cfg-path', '/tmp/tmpd6o7_3ww']
[2023-10-31T16:43:01.698-0500] {standard_task_runner.py:83} INFO - Job 17: Subtask hola_clase
[2023-10-31T16:43:01.871-0500] {task_command.py:389} INFO - Running <TaskInstance: Bash_Operator.hola_clase scheduled__2023-10-31T00:00:00+00:00 [running]> on host DESKTOP-D8R6NL8.
[2023-10-31T16:43:01.985-0500] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Bash_Operator
AIRFLOW_CTX_TASK_ID=hola_clase
AIRFLOW_CTX_EXECUTION_DATE=2023-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-31T00:00:00+00:00
[2023-10-31T16:43:01.986-0500] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-10-31T16:43:01.988-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo"Hola Mundo en MLOps"']
[2023-10-31T16:43:02.000-0500] {subprocess.py:86} INFO - Output:
[2023-10-31T16:43:02.032-0500] {subprocess.py:93} INFO - /bin/bash: line 1: echoHola Mundo en MLOps: command not found
[2023-10-31T16:43:02.033-0500] {subprocess.py:97} INFO - Command exited with return code 127
[2023-10-31T16:43:02.069-0500] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/oscar_rincon/code/oscar-rincon/ml-engineering-course/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-10-31T16:43:02.079-0500] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=Bash_Operator, task_id=hola_clase, execution_date=20231031T000000, start_date=20231031T214301, end_date=20231031T214302
[2023-10-31T16:43:02.115-0500] {standard_task_runner.py:100} ERROR - Failed to execute job 17 for task hola_clase (Bash command failed. The command returned a non-zero exit code 127.; 402422)
[2023-10-31T16:43:02.148-0500] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-10-31T16:43:02.180-0500] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
